### ISSUE TITLE
integration installs & connects to KAKU cloud without but can't retrieve status/set command

### ISSUE THREAD

**Issue by nickkindt** [rdegraafwhizzkit/ics2000-hass#1]
In a Home-assistant Docker container (synology DSM),
- the integration installs without a problem,
- it can retrieve all the entities, but retrieves them without a unique ID
- it can not retrieve status/set command of the entities,
- no error is found in the logs.
![2023-01-09 23_09_17-Instellingen – Home Assistant](https://user-images.githubusercontent.com/42751562/211418386-64cf4504-76cb-416f-be2b-a68f8e7e601a.png)

**Comment by rdegraafwhizzkit** [comment]
Hi Nick,

* You mention that the unique is not retrieved. How do you know that that is the case? Your screenshot looks similar to mine, so I trust the ics2000 hub correctly returns the devices.
* retrieving the status of KAKU devices would be great but to the best of my knowledge that is not possible with lights and switches. That's the reason one is able to configure the number of times to repeat a signal.
* which card did you use to switch on/off a light or switch? the light- or button card should be able to do the trick

Rutger

**Comment by nickkindt** [comment]
Hi Ruther,

- thank you for answering so quick!  You're right, it does work, but I was trying zigbee switches and that doesn't work. That in combination of the message below got me confused  
![2023-01-12 00_29_15-Settings – Home Assistant](https://user-images.githubusercontent.com/42751562/211944138-60fcb1d9-379d-4c25-95fc-e6a1e96c82d8.png)

- I finally found the thread were this code was more or less build and there I saw that you've written that this code for HA only works for KAKU switches and dimmers.

- Half of my devices are KAKU swichtes and dimmers, the other have are zigbee switches & zigbee RGB devices. I saw in that thread that some more or less found a way to control the zigbee devices. So my question is, is the limitation due to the fact that you did not implement it [ICS2000-HASS] or that it's not implemented [ics2000-python]

- Last and final question, does this use the web-api or controlls the devices directly on the LAN. Because now I have a 3-4s delay when I control the light from HA and a 0.5s delay from the app (if it's connected locally)

kind regards,
Nick

**Comment by rdegraafwhizzkit** [comment]
Hi Nick,

Please excuse my late reply:

* I do not own any Zigbee stuff yet so I am not able to kind of reliably test if they work. I know that in the library that I wrote that this repo is using there is some code for Zigbee. Any development work on that would be much appreciated.
* It uses the web API via HTTPS. On you LAN I think it switches to UDP messaging iso HTTPS so no, there is nothing I can do about it unless those UDP messages get decoded.

I'm gonna be working in the manifest.json file to allow for some smoother install. Thanks for working along.

Rutger
