### ISSUE TITLE
P1 support?

### ISSUE THREAD

**Issue by mverdonk77** [rdegraafwhizzkit/ics2000-hass#2]
I have been able to get it installed and working. But I was wondering whether it is possible to read the P1 interface too?
I see this plugin was inspired from Stijn-Jacobs Master, but I also see one fork of that (https://github.com/bp-ouhaha/ICS2000-Python), which has been able to get this working (?).

Perhaps it is possible to get it to work in this plugin too?

I am sorry, I do not have any experience in Python myself, so I wouldn't even know where to start.

**Comment by rdegraafwhizzkit** [comment]
Hiya, thanks for thinking along. 'Reading' the P1 port on the ICS-2000 is only possible by doing an API call to the Trust Smartcloud service. I have not implemented that nor do I plan to do so. You are far better of buying a cheap FTDI USB to P1 adapter (search for 'Slimme meter kabel - P1 USB') Home Assistant has built-in support for those adapters and it updates much faster and more reliable! Good luck.
