### ISSUE TITLE
Somfy Blinds

### ISSUE THREAD

**Issue by morrisjanssen01** [rdegraafwhizzkit/ics2000-hass#4]
Hi,
I used your integration and it works perfectly. There is just one thing. The blinds get recognized as lights. They can open and close from the Kaku app. It's Somfy RTS so doesn't report back a state. When I add it in HA, it gives me a light switch that can only open it. How do I solve this?

**Comment by Emmen75** [comment]
Hi,
I have exactly the same challenge. All the lights are working fine, but the sunscreen isn't going up or down.
In the klikaanklikuit app, the sunscreen is configured using 'somft rts - sunscreen'. The buttons within this app are also slightly different (up, down and pauze/stop).
Within the HA integration, the 'sunscreen' item is recognised/imported, but it only has an on/off button and these do not trigger the action in klikaanklikuit.

Should I change the 'light' in de code with something else, of add a second integration with the same details but change light in switch?
Regards,
Frank

**Comment by rdegraafwhizzkit** [comment]
Please see https://github.com/rdegraafwhizzkit/ics2000-hass/issues/3. Somfy is not supported as I do not own such equipment. Anyone with coding skills AND Somfy hardware is more than welcome to contribute ;)
