### ISSUE TITLE
On initial light.turn_on brightness is not controlled

### ISSUE THREAD

**Issue by UnBornLord** [rdegraafwhizzkit/ics2000-hass#6]
When calling the service light.turn_on, including data for setting the brightness to a certain level, the light turns on at it's previous set brightness. The brightness before light turned off. When calling the command for the second time, te correct brightness is set.
Also with the custom slider entity the lights are initially not set to the requested brightness. When changing the brightness it does adapt the requested value.

In practice / random case: 
- at daytime the lights were set to 90%. 
- switched off (by HA, or KAKU, or wall-switch, or whatverer)
- in the evening by service light.turn_on with brightness 25%, the light go back on at 90%, which is not convenient for my eys.

Running HA, with your resp installed via HACS.
icw KAKU ICS-2000.
Controlling several KAKU mini-dimmers, all with the same result.

**Comment by rdegraafwhizzkit** [comment]
Sorry for the late reply. The KAKU entities do not emit state, they are receive only. I get your point, but there is no way of knowing the brightness or on/off state in case another remote has changed on of those values. If one is to only control the entities from HA, it may work.
