### ISSUE TITLE
Zigbee controller

### ISSUE THREAD

**Issue by JesperVerschoor** [rdegraafwhizzkit/ics2000-hass#7]
Hello,

I'm a happy user of the integration for my kaku controlled lights for some period now.

There is however a challenge left that I haven't solved yet. I have a Zigbee 3.0 controller connected with my ics2000, which I cant succesfully control. What I've tried
- button card: toggle light
- button card: call service light_on
- script to call service light_on 2, but also 3 consecutive times

Result:
When using the service light_on the led strip turns on for a second and then switches of again. It doesn't matter if I use the script or not.

My guess is that the ICS2000 is able to somehow know the status of the zigbee based controller and overwrites my command again. The reason for this my guessing is because of the hint in the KaKu app. It shows the On (green) / Off (red) button in color depending the status.

Have you ever heard about a similar case? And if so do you have a clue how to solve it :)?

My controller:
![20231010_213839](https://github.com/rdegraafwhizzkit/ics2000-hass/assets/131768923/b1a8a4ee-b918-40b7-b22a-9edc7350f011)
Led strip off:
![Screenshot_20231010_223514_KlikAanKlikUit](https://github.com/rdegraafwhizzkit/ics2000-hass/assets/131768923/118341f5-d193-4249-9e85-2b79b243f377)
Led strip on:
![Screenshot_20231010_223614_KlikAanKlikUit](https://github.com/rdegraafwhizzkit/ics2000-hass/assets/131768923/7ab4411d-4a48-4ad2-90ad-c1874144fdfe)
Normal light (as reference without the status color)
![Screenshot_20231010_223527_KlikAanKlikUit](https://github.com/rdegraafwhizzkit/ics2000-hass/assets/131768923/bb8c336c-ba52-4ae3-843d-e35511cf7a14)

HA config:
![Screenshot_20231010_224134_Home Assistant](https://github.com/rdegraafwhizzkit/ics2000-hass/assets/131768923/6f2d6fbf-7e06-4768-bc01-5d4ba8278478)
![Screenshot_20231010_224034_Home Assistant](https://github.com/rdegraafwhizzkit/ics2000-hass/assets/131768923/7d5678f9-bac0-438a-9ebc-f938e53be03e)

**Comment by rdegraafwhizzkit** [comment]
Thanks for the great comment. If I had the hardware investigation would be doable, but lacking that, I encourage everyone to fork the repo and contribute. The Kaku lights and their remotes do not keep any state at all, they are pretty 'dumb' in that sense. So anythings else that tries to set things to on or off just pushes that state/command to the device....
